### ISSUE TITLE
KeyError: 'content-range'

### ISSUE THREAD

**Issue by foozzi** [gtsystem/python-remotezip#3]
```
{'Date': 'Tue, 09 Feb 2021 22:55:52 GMT', 'Content-Type': 'application/zip', 'Transfer-Encoding': 'chunked', 'Access-Control-Allow-Origin': 'https://render.githubusercontent.com', 'content-disposition': 'attachment; filename=linux.org.ru-gallery-master.zip', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; sandbox", 'ETag': 'W/"38a196aa726d7096d14b5cd451973b0723e6c71bf8e19452b10c5f19bb703dc9"', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Authorization,Accept-Encoding, Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'X-GitHub-Request-Id': '36AA:1009:10F43E:146AD1:602312F8'}
Traceback (most recent call last):
  File "/home/user/Pycharm/esoui-parser/1.py", line 3, in <module>
    with RemoteZip('https://github.com/foozzi/linux.org.ru-gallery/archive/master.zip') as zip:
  File "/home/user/Pycharm/esoui-parser/venv/lib/python3.9/site-packages/remotezip.py", line 130, in __init__
    super(RemoteZip, self).__init__(rio)
  File "/usr/lib/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1320, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/usr/lib/python3.9/zipfile.py", line 263, in _EndRecData
    fpin.seek(0, 2)
  File "/home/user/Pycharm/esoui-parser/venv/lib/python3.9/site-packages/remotezip.py", line 104, in seek
    self.buffer = self.fetch_fun((-size, None), stream=False)
  File "/home/user/Pycharm/esoui-parser/venv/lib/python3.9/site-packages/remotezip.py", line 171, in fetch_fun
    return self.make_buffer(res, headers['Content-Range'], stream=stream)
  File "/home/user/Pycharm/esoui-parser/venv/lib/python3.9/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-range'
```

I fixed it temporarily hardcoded
in remotezip.py:170 line
```python
return self.make_buffer(res, '1-'+headers['Content-Length']+'/*', stream=stream)
```

**Comment by gtsystem** [comment]
Hi, thanks for the report. This module works only if the web server support range requests and this is clearly stated on the readme: "For this library to work, the web server hosting the archive needs to support the range header."
The objective of this module is avoiding the download of the full zip archive just to extract some of its member or list the content so in the case range requests are not supported, a local download and unzip is more efficient and consumes less ram. The new version 0.9.3 will now fail with a more explicit error :

`remotezip.RangeNotSupported: The server doesn't support range requests`
